import React, { useState, useEffect } from 'react';
import { ShieldAlert, Filter, Eye, CheckCircle2 } from 'lucide-react';
import StatusBadge from '../components/StatusBadge';
import { doc, updateDoc } from 'firebase/firestore';
import { COLLECTIONS, subscribeToCollection } from '../firebase/firestoreService';
import { db } from '../firebase/config';
import { MOCK_RECENT_EVENTS } from '../utils/mockData';

const AlertsPage = () => {
  const [alerts, setAlerts] = useState([]);
  const [selectedAlert, setSelectedAlert] = useState(null);
  const [filterSeverity, setFilterSeverity] = useState('ALL');

  useEffect(() => {
    const unsub = subscribeToCollection(COLLECTIONS.ALERTS, (data) => {
      if (data && data.length > 0) {
        setAlerts(data);
      } else {
        setAlerts(MOCK_RECENT_EVENTS);
      }
    });
    return () => unsub();
  }, []);

  const handleResolveAlert = async (alt) => {
    if (alt._docId || alt.id) {
      try {
        const docRef = doc(db, COLLECTIONS.ALERTS, alt._docId || alt.id);
        await updateDoc(docRef, { status: 'RESOLVED', updatedAt: new Date().toISOString() });
      } catch (err) {
        console.warn('Alert update warning:', err);
      }
    }
    setSelectedAlert(null);
  };

  const filteredAlerts = alerts.filter((a) => {
    if (filterSeverity === 'ALL') return true;
    return (a.severity || '').toUpperCase() === filterSeverity;
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between p-5 rounded-2xl bg-slate-900 border border-slate-800">
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-xl bg-cyan-950/80 border border-cyan-500/40 text-cyan-400">
            <ShieldAlert className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold font-mono text-white">Rule-Based Threat Detection Engine</h2>
            <p className="text-xs text-slate-400">Real-time normalized alert stream generated by active SOC detection rules.</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-slate-400" />
          {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((sev) => (
            <button
              key={sev}
              onClick={() => setFilterSeverity(sev)}
              className={`px-3 py-1 rounded text-xs font-mono font-semibold transition-colors ${
                filterSeverity === sev
                  ? 'bg-cyan-500/20 text-cyan-400 border border-cyan-500/40'
                  : 'bg-slate-800 text-slate-400 hover:text-white'
              }`}
            >
              {sev}
            </button>
          ))}
        </div>
      </div>

      {/* Alerts Table */}
      <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-800 text-[11px] font-mono uppercase text-slate-400 bg-slate-950/40">
                <th className="py-2.5 px-3">Alert ID</th>
                <th className="py-2.5 px-3">Timestamp</th>
                <th className="py-2.5 px-3">Severity</th>
                <th className="py-2.5 px-3">Detection Rule</th>
                <th className="py-2.5 px-3">Source / Dest IP</th>
                <th className="py-2.5 px-3">MITRE</th>
                <th className="py-2.5 px-3">Status</th>
                <th className="py-2.5 px-3 text-right">Inspect</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-xs font-mono">
              {filteredAlerts.map((alt) => (
                <tr key={alt.id || alt.title} className="hover:bg-slate-800/40 transition-colors">
                  <td className="py-3 px-3 font-bold text-cyan-400">{alt.id || 'ALT-NEW'}</td>
                  <td className="py-3 px-3 text-slate-400">{alt.timestamp || 'Just Now'}</td>
                  <td className="py-3 px-3">
                    <StatusBadge level={alt.severity} />
                  </td>
                  <td className="py-3 px-3 text-slate-200 font-sans font-medium">{alt.title}</td>
                  <td className="py-3 px-3 text-slate-300">{alt.sourceIp} → {alt.destIp}</td>
                  <td className="py-3 px-3">
                    <span className="px-2 py-0.5 rounded bg-cyan-950 text-cyan-400 border border-cyan-500/30 text-[10px]">
                      {alt.mitre || 'T1110'}
                    </span>
                  </td>
                  <td className="py-3 px-3">
                    <StatusBadge level={alt.status} />
                  </td>
                  <td className="py-3 px-3 text-right">
                    <button
                      onClick={() => setSelectedAlert(alt)}
                      className="p-1.5 rounded bg-slate-800 hover:bg-slate-700 text-cyan-400"
                    >
                      <Eye className="w-4 h-4" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Inspect Modal */}
      {selectedAlert && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="w-full max-w-lg p-6 rounded-2xl bg-slate-900 border border-slate-800 space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono text-cyan-400 font-bold">{selectedAlert.id}</span>
              <StatusBadge level={selectedAlert.severity} />
            </div>
            <h3 className="text-base font-bold font-mono text-white">{selectedAlert.title}</h3>
            <p className="text-xs text-slate-300">Telemetry evidence matches detection rule <code className="text-cyan-400">{selectedAlert.rule || 'R-SSH-BRUTE'}</code></p>
            <div className="p-3 rounded bg-slate-950 text-xs font-mono text-slate-300 space-y-1">
              <p>Source IP: {selectedAlert.sourceIp}</p>
              <p>Target IP: {selectedAlert.destIp}</p>
              <p>MITRE Technique: {selectedAlert.mitre}</p>
              <p>Current Status: <span className="text-cyan-400">{selectedAlert.status}</span></p>
            </div>
            <div className="flex justify-end gap-2">
              <button
                onClick={() => setSelectedAlert(null)}
                className="px-4 py-2 rounded bg-slate-800 text-xs font-mono text-slate-300"
              >
                Close
              </button>
              {selectedAlert.status !== 'RESOLVED' && (
                <button
                  onClick={() => handleResolveAlert(selectedAlert)}
                  className="px-4 py-2 rounded bg-emerald-600 hover:bg-emerald-500 text-xs font-mono font-bold text-white flex items-center gap-1.5"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Mark Resolved</span>
                </button>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AlertsPage;
